pub fn skill_name_to_api_string(input: &str) -> Option<&'static str> {
    match input {
        "Linear equations in one variable" => Some("algebra__linear_1d"),
        "Linear equations in two variables" => Some("algebra__linear_2d"),
        "Finding roots of polynomials" => Some("algebra__polynomial_roots"),
        "Finding the next term in a sequence" => Some("algebra__sequence_next_term"),
        "Finding the nth term of a sequence" => Some("algebra__sequence_nth_term"),
        "Addition and subtraction" => Some("arithmetic__add_or_sub"),
        "Multiplication" => Some("arithmetic__mul"),
        "Division" => Some("arithmetic__div"),
        "Mixed arithmetic operations" => Some("arithmetic__mixed"),
        "Multiple addition and subtraction" => Some("arithmetic__add_sub_multiple"),
        "Multiple multiplication and division" => Some("arithmetic__mul_div_multiple"),
        "Addition and subtraction in different bases" => Some("arithmetic__add_or_sub_in_base"),
        "Nearest integer root" => Some("arithmetic__nearest_integer_root"),
        "Simplifying surds" => Some("arithmetic__simplify_surd"),
        "Differentiation" => Some("calculus__differentiate"),
        "Differentiation using the chain rule" => Some("calculus__differentiate_composed"),
        "Finding the closest value" => Some("comparison__closest"),
        "Finding the kth largest value" => Some("comparison__kth_biggest"),
        "Pairwise comparison" => Some("comparison__pair"),
        "Sorting values" => Some("comparison__sort"),
        "Unit conversion" => Some("measurement__conversion"),
        "Time calculations" => Some("measurement__time"),
        "Base conversion" => Some("numbers__base_conversion"),
        "Place value" => Some("numbers__place_value"),
        "Division with remainder" => Some("numbers__div_remainder"),
        "Greatest common divisor" => Some("numbers__gcd"),
        "Least common multiple" => Some("numbers__lcm"),
        "Checking if a number is a factor" => Some("numbers__is_factor"),
        "Listing prime factors" => Some("numbers__list_prime_factors"),
        "Prime number checking" => Some("numbers__is_prime"),
        "Rounding numbers" => Some("numbers__round_number"),
        "Polynomial addition" => Some("polynomials__add"),
        "Collecting like terms" => Some("polynomials__collect"),
        "Expanding polynomial expressions" => Some("polynomials__expand"),
        "Composing polynomials" => Some("polynomials__compose"),
        "Evaluating polynomials" => Some("polynomials__evaluate"),
        "Identifying polynomial coefficients" => Some("polynomials__coefficient_named"),
        "Simplifying powers in polynomials" => Some("polynomials__simplify_power"),
        "Probability without replacement – outcome sets" => Some("probability__swr_p_level_set"),
        "Probability without replacement – outcome sequences" => Some("probability__swr_p_sequence"),
        _ => None,
    }
}